// Generated by localization/generate_localization.py. Do not edit by hand.
// Edit localization/strings.toml, then run the generator.
package com.rsvpnano.models

object NanoLanguages {
    const val DEFAULT = "english"

    val OPTIONS = listOf(
        "english" to "English",
        "spanish" to "Español",
        "french" to "Français",
        "german" to "Deutsch",
        "romanian" to "Română",
        "polish" to "Polski",
        "russian" to "Русский",
    )
}
